name: Nightly Alpha-Vantage dump
on:
  schedule:
    - cron: '13 3 * * *'      # every day 03:13 UTC
  workflow_dispatch:          # manual Run-workflow button
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm install node-fetch@3
      - run: node fetch.js
        env:
          AV_KEY: ${{ secrets.AV_KEY }}
      - name: Commit & push
        run: |
          git config user.name  "github-actions"
          git config user.email "action@github"
          git add data/*.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Nightly data $(date -u +'%F')"
            git push
          fi
